### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by byc601235804** [XiaoMi/pegasus-python-client#13]
tools.py
line 31

error_types.ERR_OBJECT_NOT_FOUND 没这个 ERR_OK 属性
这里写错了，多写了一段 ERR_OBJECT_NOT_FOUND

return error_types.ERR_OK.value 
解决

**Comment by acelyc111** [comment]
多谢，已修复
请问你是怎么发现这个问题的呢？

**Comment by byc601235804** [comment]
> 多谢，已修复
> 请问你是怎么发现这个问题的呢？

调用 sample.py 的示例，对于 key 存在，有返回值的返回，就会直接抛出异常
