### ISSUE TITLE
Wrong partition_hash calculated

### ISSUE THREAD

**Issue by hycdong** [XiaoMi/pegasus-python-client#9]
In order to get partition index, we need to calculate partition_hash by hash_key or blob_key(hash_key and sort_key). However, client partition_hash is not equal to the partition_hash calculated by server. 

The wrong hash_value does not lead to write data to incorrect partition, but server will check equality between client partition_hash and the value calculated by itself if client partition_hash is not zero. 

As a result, we should fix this bug

**Comment by qinzuoyan** [comment]
"client partition_hash is not equal to the partition_hash calculated by server", but why "the wrong hash_value does not lead to write data to incorrect partition"?

**Comment by hycdong** [comment]
python client does not handle sign bit properly, we use partition_hash mod partition_count to get partition index. It seems that incorrect sign bit does not affect modulo operator.
My pull request: https://github.com/XiaoMi/pegasus-python-client/pull/10
